// frontend/src/app/auth/layout.tsx
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ html/body は書かない。children をラップするだけ
  return <div className="auth-layout">{children}</div>;
}
